DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
        ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        CONSTRAINT AUTHOR_UNIQ UNIQUE (NAME)
    );
COMMENT ON TABLE AUTHOR IS 'Авторы';
COMMENT ON COLUMN AUTHOR.ID IS 'Идентификатор';
COMMENT ON COLUMN AUTHOR.NAME IS 'Ф.И.О. автора';


DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
        ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        CONSTRAINT GENRE_UNIQ UNIQUE (NAME)
    );
COMMENT ON TABLE GENRE IS 'Авторы';
COMMENT ON COLUMN GENRE.ID IS 'Идентификатор';
COMMENT ON COLUMN GENRE.NAME IS 'Наименование';


DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
        ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        TITLE VARCHAR(255) NOT NULL,
        AUTHOR_ID BIGINT NOT NULL,
        GENRE_ID BIGINT NOT NULL,
        FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT BOOK_UNIQ UNIQUE (TITLE, AUTHOR_ID, GENRE_ID)
    );
COMMENT ON TABLE BOOK IS 'Книги';
COMMENT ON COLUMN BOOK.ID IS 'Идентификатор';
COMMENT ON COLUMN BOOK.TITLE IS 'Название';
COMMENT ON COLUMN BOOK.AUTHOR_ID IS 'Идентификатор автора';
COMMENT ON COLUMN BOOK.GENRE_ID IS 'Идентификатор жанра';